/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lojadeinstrumentos.view;

import com.mycompany.lojadeinstrumentos.view.CadastroClienteProduto;
import javax.swing.JOptionPane;

/**
 *
 * @author alexsandro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btniniciarCompra = new javax.swing.JButton();
        btnCadastros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVendas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuManutencao = new javax.swing.JMenu();
        mnuRelatorios = new javax.swing.JMenuItem();
        mnuCadastrosEConsultas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuFecharProgama = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setForeground(java.awt.Color.black);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btniniciarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Venda.png"))); // NOI18N
        btniniciarCompra.setMnemonic('1');
        btniniciarCompra.setText("Iniciar venda  alt + 1");
        btniniciarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btniniciarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 250, 80));

        btnCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastro.png"))); // NOI18N
        btnCadastros.setMnemonic('2');
        btnCadastros.setText("Efetuar um cadastro");
        btnCadastros.setMaximumSize(new java.awt.Dimension(97, 22));
        btnCadastros.setMinimumSize(new java.awt.Dimension(97, 22));
        btnCadastros.setPreferredSize(new java.awt.Dimension(97, 22));
        btnCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 250, 80));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tocada Quente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 80));

        btnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-pequeno.jpg"))); // NOI18N
        getContentPane().add(btnVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        mnuManutencao.setMnemonic('2');
        mnuManutencao.setText("Manutençao");

        mnuRelatorios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuRelatorios.setText("Relatorios");
        mnuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatoriosActionPerformed(evt);
            }
        });
        mnuManutencao.add(mnuRelatorios);

        mnuCadastrosEConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadastrosEConsultas.setText("Cadastros e consultas");
        mnuCadastrosEConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrosEConsultasActionPerformed(evt);
            }
        });
        mnuManutencao.add(mnuCadastrosEConsultas);

        jMenuBar1.add(mnuManutencao);

        jMenu1.setText("Saida");

        mnuFecharProgama.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuFecharProgama.setText("Fechar Progama");
        mnuFecharProgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFecharProgamaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFecharProgama);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniniciarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarCompraActionPerformed
    /* criando o  obj de venda para chamar a tela de vendas.   */
        TelaVendas venda = new TelaVendas();
        
    venda.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btniniciarCompraActionPerformed

    private void mnuFecharProgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFecharProgamaActionPerformed
     /* fechar o programa */
     /* validando a resposta do usuario na caixa de confirmar dialogo do JOptionPane, se caso a resposta for nao o retorno é 1, se caso  cancelar é 2 e se caso fechar é -1 
     como so vai fecharo o progama se a pessoa clicar em sim, o if valida se a resposta for igual a 0 se nao for, o progama nao faz nada ..*/
        int resposta = JOptionPane.showConfirmDialog(null, " Deseja fechar o Programa ?");

        if (resposta == 0) {
            System.exit(0);
        }     
     //System.exit(0);     

    }//GEN-LAST:event_mnuFecharProgamaActionPerformed

    private void mnuCadastrosEConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrosEConsultasActionPerformed
        CadastroClienteProduto novoCadastro = new CadastroClienteProduto();
        novoCadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuCadastrosEConsultasActionPerformed

    private void btnCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrosActionPerformed
        CadastroClienteProduto novoCadastro = new CadastroClienteProduto();
        novoCadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrosActionPerformed

    private void mnuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatoriosActionPerformed
            Relatorios relatoriosTela = new Relatorios();
            relatoriosTela.setVisible(true);
                    // TODO add your handling code here:
    }//GEN-LAST:event_mnuRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastros;
    private javax.swing.JLabel btnVendas;
    private javax.swing.JButton btniniciarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCadastrosEConsultas;
    private javax.swing.JMenuItem mnuFecharProgama;
    private javax.swing.JMenu mnuManutencao;
    private javax.swing.JMenuItem mnuRelatorios;
    // End of variables declaration//GEN-END:variables
}
